### ISSUE TITLE
Oppdatering av ansattkart i BOD

### ISSUE THREAD

**Issue by CathrineBast** [Altinn/altinn-brukerservice#15]
https://digdir.sharepoint.com/:x:/r/sites/msteams_64b443/_layouts/15/Doc.aspx?sourcedoc=%7BB1D7A7A8-C5C9-4C7F-B7A6-B25F80202E4F%7D&file=Ansattekart%20lokaler%20i%20Br%20sund.xlsx&action=default&mobileredirect=true

- [x] oppdatere og korrigere kartet med nye plasser
- [ ] Legge til alle ansatte
- [ ] informere Hege at det er klart
- [ ] Hege informerer komm ang event nyhetssak om oppdateringen
```[tasklist]
### Tasks
```

**Comment by CathrineBast** [comment]
nå er det litt endring i hvor folk sitter så vi avventer litt
