### ISSUE TITLE
English Refresher ABS 2023_2024

### ISSUE THREAD

**Issue by BostonElf** [Altinn/altinn-brukerservice#2]
- [ ] Definer omfang , fokusområde ->spørreundersøkelse hos kollleger - Hva trenger du eller savner du for å bli bedre ?
- [ ] Finn nøkkelord og nøkkelfraser
- [ ] Skikk og bruk
- [ ] Tilordne materiale
- [ ] Lag Powerpoint
- [ ] Feedback til neste versjon eller neste input
```[tasklist]
### Tasks
```
