### ISSUE TITLE
Bestille stoler, inventar og utstyr til BOD

### ISSUE THREAD

**Issue by Hegemarie** [Altinn/altinn-brukerservice#7]
- [x] - [x] Tell over møterom og stoler
- [x] Innhent tilbud
- [x] snakk med huseier
- [x] Be om revidering av budsjett inventar
- [x] Bestill inventar som mangler
```[tasklist]
### Tasks
```
